config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  resources :startups do
    resources :investments
  end

  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/startup.rb
class Startup < ApplicationRecord
    has_many :investments, dependent: :destroy
    validates :name, presence: true, length: { minimum: 6 }
end

app/controllers/startups_controller.rb
class StartupsController < ApplicationController
    helper JanuaryPromotionHelper
    before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

    def index
        @startups = Startup.all
    end

    def show
        @startup = Startup.find(params[:id]);
    end

    def new
        @startup = Startup.new
    end

    def edit
        @startup = Startup.find(params[:id])
    end

    def create
        @startup = Startup.new(startup_params)

        if @startup.save
            redirect_to @startup
        else
            render 'new'
        end
    end

    def update
        @startup = Startup.find(params[:id])
       
        if @startup.update(startup_params)
          redirect_to @startup
        else
          render 'edit'
        end
    end

    def destroy
        @startup = Startup.find(params[:id])
        @startup.destroy

        redirect_to startups_path
    end

    private
        def startup_params
            params.require(:startup).permit(:name, :description)
        end
end

app/helpers/startups_helper.rb
module StartupsHelper
end

app/views/startups/_form.html.erb
<%= form_with model: @startup, local: true do |form| %>
 
  <% if @startup.errors.any? %>
    <div class="alert alert-danger">
      <%= pluralize @startup.errors.count, "error" %> prohibited this startup from being saved:
      <ul>
        <% @startup.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form-group">
    <div class="textfield-box">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>
 
  <div class="form-group">
    <div class="textfield-box">
      <%= form.label :description %>
      <%= form.text_area :description, class: 'form-control' %>
    </div>
  </div>
 
  <p>
    <%= form.submit class: 'btn' %>
  </p>
 
<% end %>

app/views/startups/edit.html.erb
<div class="card">
    <div class="card-header d-flex">
        <h3 class="card-title mb-0">
            Edit startup
        </h3>
    </div>
    <div class="card-body">
        <%= render 'form' %>
    </div>
</div>

app/views/startups/index.html.erb
<div class="card">
    <div class="card-header d-flex pr-0">
        <h5 class="card-title mb-0">Startups</h5>
        <% if user_signed_in? %>
            <div class="card-actions ml-auto py-0">
                <%= link_to 'New startup', new_startup_path, class: 'btn btn-primary' %>
            </div>
        <% end %>
    </div>
    <table class="table mb-0">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @startups.each do |startup| %>
                <tr>
                    <td scope="row"><%= startup.name %></td>
                    <td><%= startup.description %></td>
                    <td>
                        <%= link_to 'Show', startup_path(startup), class: 'btn btn-sm' %>
                        <% if user_signed_in? %>
                            <%= link_to 'Edit', edit_startup_path(startup), class: 'btn btn-sm' %>
                            <%= link_to 'Delete', startup_path(startup),
                                method: :delete,
                                data: { confirm: 'Are you sure?' },
                                class: 'btn btn-sm' %>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/startups/new.html.erb
<div class="card">
    <div class="card-header d-flex">
        <h3 class="card-title mb-0">
            New Startup
        </h3>
    </div>
    <div class="card-body">
        <%= render 'form' %>
    </div>
</div>

app/views/startups/show.html.erb
<div class="card">
    <div class="card-header d-flex">
        <h3 class="card-title mb-0">
            <%= @startup.name %>
        </h3>
        <% if user_signed_in? %>
            <div class="card-actions ml-auto py-0">
                <%= link_to 'Edit', edit_startup_path(@startup), class: 'btn btn-primary' %>
            </div>
        <% end %>
    </div>
    <div class="card-body">
        <p class="card-text">
            <%= @startup.description %>
        </p>
        <p>
            Total invested: <%= number_to_currency(@startup.investments.sum(:amount)) %>
        </p>
    </div>
</div>

<% if user_signed_in? %>
    <div class="card mt-3">
        <div class="card-header d-flex pr-0">
            <h5 class="card-title mb-0">Your Investments</h5>
        </div>
        <table class="table mb-0">
            <thead>
                <tr>
                    <th scope="col">Amount</th>
                    <th scope="col">Wallet amount</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                <%= render @startup.investments.where(user_id: current_user.id) %>
            </tbody>
        </table>
    </div>

    <div class="card mt-3">
        <div class="card-header d-flex pr-0">
            <h5 class="card-title mb-0">January promotion</h5>
        </div>
        <table class="table mb-0">
            <thead>
                <tr>
                    <th scope="col">Límite inferior</th>
                    <th scope="col">Límite superior</th>
                    <th scope="col">Bonificación</th>
                </tr>
            </thead>
            <tbody>
                <% january_promotion_table(current_user).each do |row| %>
                    <tr>
                        <td scope="row"><%= number_to_currency row[:lower_limit] %></td>
                        <td><%= number_to_currency row[:upper_limit] %></td>
                        <td><%= number_to_percentage row[:bonus] %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>

    <div class="card mt-3">
        <div class="card-header d-flex">
            <h3 class="card-title mb-0">
                Invest
            </h3>
        </div>
        <div class="card-body">
            <%= render 'investments/form' %>
        </div>
    </div>
<% end %>