config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  resources :startups do
    resources :investments
  end

  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div id="footer" class="fixed-bottom">
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-primary">
    <div class="container">
        <%= link_to 'Play Business', root_path, class: 'navbar-brand' %>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <%= link_to 'Startups', startups_path, class: 'nav-link' %>
            </li>
        </ul>
        <% if user_signed_in? %>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to 'Update account', edit_user_registration_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Sign out', destroy_user_session_path, data: { confirm: "Are you sure?" }, method: :delete, class: 'nav-link' %>
                </li>
            </ul>
        <% else %>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
                </li>
            </ul>
        <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Playbusiness</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <main class="p-3">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </main>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>